tezosmonsters:
  jjwt:
    secret: Pyw7Daewoidij343uxvXjrIWt6goPiJhJaFG8cUPvh8
    expirationAccess: 10000
    expirationRefresh: 100000

  factory:
    pictures_folder: pictures


spring:
  data:
    mongodb.uri: mongodb+srv://root:wrikeTest2019@cluster0-j70uo.mongodb.net/contract_dev?retryWrites=true&w=majority

logging:
  level:
    web: debug
